blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, handler404
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('magazine.urls', 'magazine'), namespace='magazine')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'magazine.views.error_404'
handler500 = 'magazine.views.error_500'

magazine/urls.py
from django.urls import path, reverse_lazy
from . views import (
    SignUpView, HomePageView, loginUser, logoutUser, profile_page,
    edit_profile, PostsView, PostDetailView, CreatePost, UpdatePost,
    DeletePost, UserPosts, DeleteComment, AdminPage, AdminDeleteComment,
    AdminDeletePost)
from django.contrib.auth.views import (
    PasswordChangeView, PasswordChangeDoneView)

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('posts/', PostsView.as_view(), name='posts'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', loginUser, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('profile/<username>/', profile_page, name='profile'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html', success_url=reverse_lazy(
            'magazine:password_change_done')), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('post/<pk>/<slug:slug>/', PostDetailView.as_view(),
         name='post_detail'),
    path('create/', CreatePost.as_view(), name='post_create'),
    path('update/<pk>/<slug:slug>/', UpdatePost.as_view(), name='post_update'),
    path('delete/<pk>/<slug:slug>/', DeletePost.as_view(), name='post_delete'),
    path('profile/posts/<username>', UserPosts.as_view(), name='user_posts'),
    path('delete/comment/<pk>', DeleteComment.as_view(),
         name='comment_delete'),
    path('admin-page/', AdminPage.as_view(), name='admin_page'),
    path('admin-delete/comment/<pk>', AdminDeleteComment.as_view(),
         name='admin_comment_delete'),
    path('admin-delete/<pk>/<slug:slug>/', AdminDeletePost.as_view(),
         name='admin_post_delete'),

]

magazine/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from cloudinary.models import CloudinaryField


class User(AbstractUser):
    """
    Class that requests information from the user
    """
    email = models.EmailField('email adress', blank=False, unique=True)
    username = models.CharField(max_length=100, blank=True, unique=True)
    account_created = models.DateField(auto_now_add=True)
    USERNAME_FIELD = 'username'


class Post(models.Model):
    title = models.CharField(max_length=50, unique=True, db_index=True)
    slug = models.SlugField(max_length=50, db_index=True)
    article_description = models.CharField(max_length=100, null=True)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    post_created = models.DateTimeField(auto_now_add=True)
    post_updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='', blank=False, null=True)

    class Meta:
        ordering = ['-post_created']

    def __str__(self):
        return self.title


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    image = models.ImageField(null=False, blank=False, upload_to='magazine/',
                              default='magazine/default_avatar')
    bio = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.user.username


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(max_length=300)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_created = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=True)

    class Meta:
        ordering = ('comment_created',)

    def __str__(self):
        return 'Comment by {}'.format(self.user)

magazine/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . models import User, Comment, Profile


class SignUpForm(UserCreationForm):
    password1 = forms.CharField(
        label='Password', widget=forms.PasswordInput(
            attrs={
                'class': 'input-area form-control',
                'placeholder': 'Password', }))
    password2 = forms.CharField(
        label='Confirm Password', widget=forms.PasswordInput(
            attrs={
                'class': 'input-area form-control',
                'placeholder': 'Confirm Password',
                }))

    class Meta:
        model = User
        fields = ['username', 'email']
        widgets = {
            'username': forms.TextInput(attrs={
                'placeholder': 'Username',
                'class': 'input-area form-control', }),
            'email': forms.EmailInput(attrs={
                'placeholder': 'Email',
                'class': 'input-area form-control', })
        }


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'input-area form-control',
            'placeholder': 'Username', }))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'input-area form-control',
            'placeholder': 'Password', }))


class ProfileForm(forms.Form):
    image = forms.ImageField(required=False)
    bio = forms.CharField(
        widget=forms.Textarea(), max_length=500, required=False)
    username = forms.CharField(max_length=100)

    def __init__(self, old_username, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.old_username = old_username

    def clean_username(self):
        """
        Displays error if username is taken
        """
        username = self.cleaned_data['username']
        if username != self.old_username:
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError(
                    'Username is taken')
        return username


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {
            'user': forms.TextInput(attrs={
                'placeholder': 'Username',
                'class': 'input-area form-control', }),
            'content': forms.TextInput(attrs={
                'placeholder': 'Comment',
                'class': 'input-area form-control', })
        }

magazine/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (
    CreateView, ListView, DetailView, UpdateView, DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import SignUpForm, LoginForm, ProfileForm, CommentForm
from django.urls import reverse_lazy
from .models import Post, User, Profile, Comment


class HomePageView(ListView):
    """
    This class shows all posts, and adds the newest post on top of the page.
    The posts are ordered by date in decreasing order.
    """

    template_name = 'magazine/home.html'
    queryset = Post.objects.all()
    paginate_by = 6


class PostsView(ListView):
    """
    This class shows all posts, and adds the newest post on top of the page.
    The posts are ordered by date in decreasing order.
    """
    template_name = 'magazine/posts.html'
    queryset = Post.objects.all()


class SignUpView(CreateView):
    """
    This function handles the signup view.
    When user has created their account they get redirected to the login page.
    """
    template_name = 'users/signup.html'
    success_url = reverse_lazy('magazine:login')
    form_class = SignUpForm


def loginUser(request):
    """
    This function handles the login form.
    If the username and password is valid they log in and get redirected
    to the home page.
    If the username or password is invalid a error message will display
    on the page.
    """
    if request.user.is_authenticated:
        return redirect('magazine:home')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'You have successfully logged in')
                return redirect('magazine:home')
            else:
                messages.warning(request, 'Invalid username or Password')
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form': form})


def logoutUser(request):
    logout(request)
    messages.success(request, 'You have successfully logged out')
    return redirect('magazine:login')


# Rouizi
@login_required
def profile_page(request, username):
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    return render(request, 'users/profile.html', {
        'profile': profile, 'user': user})


# Rouizi
@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.user.username, request.POST, request.FILES)
        if form.is_valid():
            bio = form.cleaned_data["bio"]
            username = form.cleaned_data["username"]
            image = form.cleaned_data["image"]

            user = User.objects.get(id=request.user.id)
            profile = Profile.objects.get(user=user)
            user.username = username
            user.save()
            profile.bio = bio
            messages.success(request, 'Profile successfully changed')
            if image:
                profile.image = image
            profile.save()
            return redirect("magazine:profile", username=user.username)
    else:
        form = ProfileForm(request.user.username)
    return render(request, "users/edit_profile.html", {"form": form})


# Rouizi
class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']
        slug = self.kwargs['slug']

        post = get_object_or_404(Post, pk=pk, slug=slug)
        form = CommentForm()
        comments = post.comment_set.all()

        context['comments'] = comments
        context['form'] = form
        context['post'] = Post.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        self.object = self.get_object()
        context = super().get_context_data(**kwargs)

        post = Post.objects.filter(id=self.kwargs['pk'])[0]
        comments = post.comment_set.all()

        context['comments'] = comments
        context['form'] = form
        context['post'] = post

        if form.is_valid():

            user = self.request.user
            content = form.cleaned_data['content']

            comment = Comment.objects.create(
                user=user, content=content, post=post)

            form = CommentForm()
            context['form'] = form
            return self.render_to_response(context=context)

        return self.render_to_response(context=context)


class CreatePost(LoginRequiredMixin, CreateView):
    """
    This class handles the form for creating post.
    Loginrequiredmixin verifies that the current user who has created the
    post is authenticated.
    """
    model = Post
    fields = ['title', 'article_description', 'content', 'image']
    success_url = reverse_lazy('magazine:home')

    def form_valid(self, form):
        """
        This function saves the post model if the form is valid.
        """
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.slug = slugify(form.cleaned_data['title'])
        self.object.save()
        return super().form_valid(form)


class UpdatePost(LoginRequiredMixin, UpdateView):
    """
    This class handles the view for updating the posts.
    This class allows only the creator of the post to update it.
    """
    model = Post
    fields = ['title', 'article_description', 'content', 'image']
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('magazine:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']
        slug = self.kwargs['slug']
        post = Post.objects.filter(id=self.kwargs['pk'])[0]
        update = True
        context['update'] = 'update'

        return context

    def get_queryset(self):
        return self.model.objects.filter(author=self.request.user)


class DeletePost(LoginRequiredMixin, DeleteView):
    """
    This class allows the user that has created a post to delete it.
    """
    model = Post
    success_url = reverse_lazy('magazine:home')

    def get_queryset(self):
        return self.model.objects.all()


class UserPosts(ListView):
    """
    This class allows a user with an account to see all the posts
    they have made in one place.
    This class adds the newest post on top of the page.
    The posts are ordered by date in decreasing order.
    """
    model = Post
    template_name = 'users/user_posts.html'
    queryset = Post.objects.all()

    def get_queryset(self):
        return self.model.objects.filter(author=self.request.user).order_by(
            '-post_created')


class DeleteComment(LoginRequiredMixin, DeleteView):
    """
    This class allows the user that has created a comment to delete it.
    """
    model = Comment
    success_url = reverse_lazy('magazine:home')

    def get_queryset(self):
        return self.model.objects.all()


class AdminPage(LoginRequiredMixin, ListView):
    """
    This class adds all the model data in one place
    for the superuser / Site Owner.
    """

    model = Post
    template_name = 'admin/admin_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = Post.objects.all()
        context['comment'] = Comment.objects.all()
        context['comments_approved'] = Comment.objects.filter(approved=True)
        context['posts'] = Post.objects.all().count()
        context['comments'] = Comment.objects.all().count()
        context['profiles'] = Profile.objects.all()
        context['users'] = User.objects.all().count()
        return context


def error_404(request, exception):
    return render(request, '404.html')


def error_500(request):
    return render(request, '500.html')

    def check():
        pass


class AdminDeletePost(LoginRequiredMixin, DeleteView):
    """
    This class allows the user that has created a post to delete it.
    """
    model = Post
    template_name = 'admin/admin_post_confirm_delete.html'
    success_url = reverse_lazy('magazine:admin_page')


class AdminDeleteComment(LoginRequiredMixin, DeleteView):
    """
    This class allows the user that has created a comment to delete it.
    """
    model = Comment
    template_name = 'admin/admin_comment_confirm_delete.html'
    success_url = reverse_lazy('magazine:admin_page')

templates/magazine/comment_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
{% if request.user.is_superuser %}
<div class="container form-container">
    <h3>Delete Comment</h3>
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete this comment?</p>
        <p>{{ comment.content }} by {{ comment.user }}</p>
        <strong>This action cannot be undone</strong>
        <div class="button-container">
            <button type="submit" value="Delete" class="btn btn-outline-dark">Delete</button>
            <a href="{% url 'magazine:post_detail' comment.post.pk comment.post.slug %}" class="btn btn-outline-dark">Cancel</a>
            </div>
    </form>
</div>
{% elif object.user == request.user %}
<div class="container form-container">
    <h3>Delete Comment</h3>
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete this comment?</p>
        <p>{{ comment.content }} by {{ comment.user }}</p>
        <strong>This action cannot be undone</strong>
        <div class="button-container">
            <button type="submit" value="Delete" class="btn btn-outline-dark">Delete</button>
            <a href="{% url 'magazine:post_detail' comment.post.pk comment.post.slug %}" class="btn btn-outline-dark">Cancel</a>
            </div>
    </form>
</div>
{% endif %}
{% endblock %}

templates/magazine/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="hero">
  <h1 class="logo">
    MAGAZINE
  </h1>
  <h2>Interior & Lifestyle</h2>
</div>
<div class="row blog-post-container">
  {% for post in object_list %}

  <div class="col post-container">
    <a class="post-image-link" href="{% url 'magazine:post_detail' post.pk post.slug %}">
      {% if post.image %}
      <img src="{{ post.image.url }}" alt="a blog post image that links to the blog post page with all of the post content {{ post.title }}" class="post-image">

      {% else %}
      <a class="post-image-link" href="{% url 'magazine:post_detail' post.pk post.slug %}">
        <img src="{% static 'img/default-post.jpg' %}" alt="a blog post image that links to the blog post page with all of the post content {{ post.title }}" class="post-image">

        {% endif %}
        <div class="post-body">
        <div class="author-created">
          <span class="">
            {{ post.author }} | {{ post.post_created }}
          </span>
          </div>
          <div class="title-description-container">
            <h2 class="post-title">{{ post.title }}</h2>
            <h3>{{ post.article_description }}</h3>
          </div>
        </div>
      </a>
  </div>
  {% endfor %}
</div>
{% endblock content %}

templates/magazine/post_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if request.user.is_superuser %}
<h1>Delete Post</h1>
<div class="form-container">
<form class="form" method="POST" enctype="multipart/form-data">

    {% csrf_token %}
<p>Are you sure you want to delete <span>{{ object }}</span>?</p>
<div class="button-container">
<button type="submit" value="Delete" class="btn btn-outline-dark">Delete</button>
<a href="{% url 'magazine:post_detail' object.pk object.slug %}" class="btn btn-outline-dark">Cancel</a>
</div>
</form>
</div>
{% elif object.author == request.user %}
<h1>Delete Post</h1>
<div class="form-container">
<form class="form" method="POST" enctype="multipart/form-data">

    {% csrf_token %}
<p>Are you sure you want to delete <span>{{ object }}</span>?</p>
<div class="button-container">
<button type="submit" value="Delete" class="btn btn-outline-dark">Delete</button>
<a href="{% url 'magazine:post_detail' object.pk object.slug %}" class="btn btn-outline-dark">Cancel</a>
</div>
</form>
</div>
{% endif %}
{% endblock content %}

templates/magazine/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="post-detail-outer">
  <div class="post-detail-container">
    <div class="post-detail-image">
      {% if object.image %}
      <img src="{{ object.image.url }}" alt="{{ object.title }}" class="post-image-detail">

      {% else %}

      <img src="{% static 'img/default-post.jpg' %}" alt="{{ object.title }}" class="post-image-detail">

      {% endif %}
    </div>
    <div class="post-text-container">
      <span>{{ object.author }} | {{ object.post_created }}</span>
      <h2>{{ object.title }}</h2>
      <h3>{{ object.article_description }}</h3>
      <p>{{ object.content }}</p>
    </div>
    {% if object.author == request.user %}
    <div class="container post-buttons">
      <a class="btn btn-outline-dark" href="{% url 'magazine:post_delete' object.pk object.slug %}">Delete</a>
      <a class="btn btn-outline-dark" href="{% url 'magazine:post_update' object.pk object.slug %}">Edit</a>
    </div>
    {% elif user.is_superuser %}
    <div class="container post-buttons">
      <a class="btn btn-outline-dark" href="{% url 'magazine:post_delete' object.pk object.slug %}">Delete</a>
    </div>
    {% endif %}
  </div>
  {% if comments %}
  <div class="user-comment-container">
    <div class="comment-count">
      <span class="badge badge-dark ml-2">{{ comments.count }}</span>
      <h3 class="comment-title" >Comment{{ comments.count|pluralize }}</h3>
    </div>
    {% for comment in comments %}
    <div class="user-comment">

      <div class="comment-content">
        <div class="comment-image-name">
          <img src="{{ comment.user.profile.image.url }}" alt="{{ user.username }}"
            class="comment-profile-image">
            <div class="comment-user-created">
          <strong> {{ comment.user }} </strong>
          <span class="muted comment-created"> {{ comment.comment_created }} </span>
          <p class="comment-text">{{ comment.content }}</p>
        </div>
        </div>
        {% if comment.user == request.user %}
        <a class="btn btn-outline-dark comment-delete-button" href="{% url 'magazine:comment_delete' comment.pk %}">Delete</a>
        {% elif user.is_superuser %}
        <a class="btn btn-outline-dark comment-delete-button" href="{% url 'magazine:comment_delete' comment.pk %}">Delete</a>
        {% endif %}
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %}
</div>
{% if user.is_authenticated %}
<div class="form-container">
  <form method="POST">
    {% csrf_token %}
    {% if form.non_field_errors %}
    {% for error in form_non_field_errors %}
    {{ error }}
    {% endfor %}
    {% endif %}

    {% for hidden in form_hidden_fields %}
    {{ hidden }}
    {% endfor %}

    {% for field in form %}
    {{ field.label_tag }}
    <div class="form-group">{{ field }}</div>
    {{ field.errors.as_ul }}
    {% endfor %}
    <button class="btn btn-outline-dark" type="submit" value="submit">Submit</button>
  </form>
</div>
{% else %}
<div class="login-to-comment-container">
  <h2 class="login-to-comment"><a class="nav-link {% if request.path == '/users/login' %}active{% endif %}" href="{% url 'magazine:login' %}">Log in&nbsp;</a> / <a class="nav-link {% if request.path == '/users/signup' %}active{% endif %}" href="{% url 'magazine:signup' %}">&nbsp;Sign up</a> &nbsp;to leave a comment</h2>
</div>
{% endif %}
{% endblock content %}

templates/magazine/post_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>Create Post</h1>
<div class="form-container">
<form class="form" method="POST" enctype="multipart/form-data">

    {% csrf_token %}
    {% if form.non_field_errors %}
    {% for error in form_non_field_errors %}
    {{ error }}
    {% endfor %}
    {% endif %}

    {% for hidden in form_hidden_fields %}
    {{ hidden }}
    {% endfor %}

    {% for field in form %}
    {{ field.label_tag }}
    <div class="form-group">{{ field }}</div>
    {{ field.errors.as_ul }}
    {% endfor %}
    <button class="btn btn-outline-dark" type="submit" value="submit">Submit</button>

</form>
</div>
{% endblock content %}

templates/magazine/post_update_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>Update Post</h1>
<div class="form-container">
<form class="form" method="POST" enctype="multipart/form-data">

    {% csrf_token %}
    {% if form.non_field_errors %}
    {% for error in form_non_field_errors %}
    {{ error }}
    {% endfor %}
    {% endif %}

    {% for hidden in form_hidden_fields %}
    {{ hidden }}
    {% endfor %}

    {% for field in form %}
    {{ field.label_tag }}
    <div class="form-group">{{ field }}</div>
    {{ field.errors.as_ul }}
    {% endfor %}
    <button class="btn btn-outline-dark" type="submit" value="Update">Submit</button>

</form>
</div>
{% endblock content %}

templates/magazine/posts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="row blog-post-container">
  {% for post in object_list %}

  <div class="col post-container">
    <a class="post-image-link" href="{% url 'magazine:post_detail' post.pk post.slug %}">
      {% if post.image %}
      <img src="{{ post.image.url }}" alt="a blog post image that links to the blog post page with all of the post content {{ post.title }}" class="post-image">

      {% else %}
      <a class="post-image-link" href="{% url 'magazine:post_detail' post.pk post.slug %}">
        <img src="{% static 'img/default-post.jpg' %}" alt="a blog post image that links to the blog post page with all of the post content {{ post.title }}" class="post-image">

        {% endif %}
<div class="post-body">
        <div class="author-created">
          <span class="">
            {{ post.author }} | {{ post.post_created }}
          </span>
        </div>
          <div class="title-description-container">
            <h2 class="post-title">{{ post.title }}</h2>
            <h3>{{ post.article_description }}</h3>
          </div>
        </div>
      </a>
  </div>
  {% endfor %}
</div>
{% endblock content %}