blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, handler404
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('magazine.urls', 'magazine'), namespace='magazine')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'magazine.views.error_404'
handler500 = 'magazine.views.error_500'

magazine/urls.py
from django.urls import path, reverse_lazy
from . views import (
    SignUpView, HomePageView, loginUser, logoutUser, profile_page,
    edit_profile, PostsView, PostDetailView, CreatePost, UpdatePost,
    DeletePost, UserPosts, DeleteComment, AdminPage, AdminDeleteComment,
    AdminDeletePost)
from django.contrib.auth.views import (
    PasswordChangeView, PasswordChangeDoneView)

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('posts/', PostsView.as_view(), name='posts'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', loginUser, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('profile/<username>/', profile_page, name='profile'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html', success_url=reverse_lazy(
            'magazine:password_change_done')), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('post/<pk>/<slug:slug>/', PostDetailView.as_view(),
         name='post_detail'),
    path('create/', CreatePost.as_view(), name='post_create'),
    path('update/<pk>/<slug:slug>/', UpdatePost.as_view(), name='post_update'),
    path('delete/<pk>/<slug:slug>/', DeletePost.as_view(), name='post_delete'),
    path('profile/posts/<username>', UserPosts.as_view(), name='user_posts'),
    path('delete/comment/<pk>', DeleteComment.as_view(),
         name='comment_delete'),
    path('admin-page/', AdminPage.as_view(), name='admin_page'),
    path('admin-delete/comment/<pk>', AdminDeleteComment.as_view(),
         name='admin_comment_delete'),
    path('admin-delete/<pk>/<slug:slug>/', AdminDeletePost.as_view(),
         name='admin_post_delete'),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://kit.fontawesome.com/215e1e67e2.js" crossorigin="anonymous"></script>
  <meta name="description" content="Magazine, where people share and get inspired by interior designs.">
  <meta name="keywords" content="interior design, interior, interior articles, design, trends">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'CSS/style.css' %}">
  <link type="image/png" sizes="32x32" rel="icon" href="{% static 'img/favicon/favicon.ico' %}">
  <title>Magazine</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'magazine:home' %}">MAGAZINE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/' %}active{% endif %}" aria-current="page"
              href="{% url 'magazine:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/posts/' %}active{% endif %}"
              href="{% url 'magazine:posts' %}">Blog</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/create/' %}active{% endif %}"
              href="{% url 'magazine:post_create' %}">Create Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.user.username in request.path %}active{% endif %}"
              href="{% url 'magazine:profile' request.user.username %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'magazine:logout' %}">Log out</a>
          </li>
          {% if user.is_superuser %}
          <li class="nav-item">
            <a href="{% url 'magazine:admin_page' %}"
              class="nav-link {% if request.path == '/admin-page/' %}active{% endif %}">Admin</a>
          </li>
          {% endif %}

          {% else %}

          <li class="nav-item">
            <a class="nav-link {% if request.path == '/login/' %}active{% endif %}"
              href="{% url 'magazine:login' %}">Log in</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/signup/' %}active{% endif %}"
              href="{% url 'magazine:signup' %}">Sign up</a>
          </li>

          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" id="messages">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endfor %}



  {% block content %}
  {% endblock content %}
  <footer>
    <div class="card text-center">
      <div class="card-header">
        Magazine
      </div>
      <div id="social-media">
        <ul class="social-media-container footer-links">
          <li>
            <a href="https://www.instagram.com/" rel="noopener" target="_blank"
              aria-label="Visit our instagram page (opens in a new tab)"><i class="fa-brands fa-instagram"></i></a>
          </li>
          <li>
            <a href="https://www.facebook.com/" rel="noopener" target="_blank"
              aria-label="Visit our facebook page (opens in a new tab)"><i class="fa-brands fa-facebook"></i></a>
          </li>
          <li>
            <a href="https://www.twitter.com/" rel="noopener" target="_blank"
              aria-label="Visit our twitter page (opens in a new tab)"><i class="fa-brands fa-twitter"></i></a>
          </li>
          <li>
            <a href="https://www.youtube.com/" rel="noopener" target="_blank"
              aria-label="Visit our youtube page (opens in a new tab)"><i class="fa-brands fa-youtube"></i></a>
          </li>

        </ul>
      </div>
      <div class="card-footer">
        &copy;Copyright 2022<br>
        Website created by Frirsta. App icon by <a href="https://icons8.com/">Icon8</a>

      </div>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js">
  </script>
  <script>
    setTimeout(function () {
      $('#messages').alert('close');
    }, 3000);
  </script>
</body>

</html>