blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, handler404
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('magazine.urls', 'magazine'), namespace='magazine')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'magazine.views.error_404'
handler500 = 'magazine.views.error_500'

magazine/urls.py
from django.urls import path, reverse_lazy
from . views import (
    SignUpView, HomePageView, loginUser, logoutUser, profile_page,
    edit_profile, PostsView, PostDetailView, CreatePost, UpdatePost,
    DeletePost, UserPosts, DeleteComment, AdminPage, AdminDeleteComment,
    AdminDeletePost)
from django.contrib.auth.views import (
    PasswordChangeView, PasswordChangeDoneView)

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('posts/', PostsView.as_view(), name='posts'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', loginUser, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('profile/<username>/', profile_page, name='profile'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html', success_url=reverse_lazy(
            'magazine:password_change_done')), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('post/<pk>/<slug:slug>/', PostDetailView.as_view(),
         name='post_detail'),
    path('create/', CreatePost.as_view(), name='post_create'),
    path('update/<pk>/<slug:slug>/', UpdatePost.as_view(), name='post_update'),
    path('delete/<pk>/<slug:slug>/', DeletePost.as_view(), name='post_delete'),
    path('profile/posts/<username>', UserPosts.as_view(), name='user_posts'),
    path('delete/comment/<pk>', DeleteComment.as_view(),
         name='comment_delete'),
    path('admin-page/', AdminPage.as_view(), name='admin_page'),
    path('admin-delete/comment/<pk>', AdminDeleteComment.as_view(),
         name='admin_comment_delete'),
    path('admin-delete/<pk>/<slug:slug>/', AdminDeletePost.as_view(),
         name='admin_post_delete'),

]

magazine/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . models import User, Comment, Profile


class SignUpForm(UserCreationForm):
    password1 = forms.CharField(
        label='Password', widget=forms.PasswordInput(
            attrs={
                'class': 'input-area form-control',
                'placeholder': 'Password', }))
    password2 = forms.CharField(
        label='Confirm Password', widget=forms.PasswordInput(
            attrs={
                'class': 'input-area form-control',
                'placeholder': 'Confirm Password',
                }))

    class Meta:
        model = User
        fields = ['username', 'email']
        widgets = {
            'username': forms.TextInput(attrs={
                'placeholder': 'Username',
                'class': 'input-area form-control', }),
            'email': forms.EmailInput(attrs={
                'placeholder': 'Email',
                'class': 'input-area form-control', })
        }


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'input-area form-control',
            'placeholder': 'Username', }))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'input-area form-control',
            'placeholder': 'Password', }))


class ProfileForm(forms.Form):
    image = forms.ImageField(required=False)
    bio = forms.CharField(
        widget=forms.Textarea(), max_length=500, required=False)
    username = forms.CharField(max_length=100)

    def __init__(self, old_username, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.old_username = old_username

    def clean_username(self):
        """
        Displays error if username is taken
        """
        username = self.cleaned_data['username']
        if username != self.old_username:
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError(
                    'Username is taken')
        return username


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {
            'user': forms.TextInput(attrs={
                'placeholder': 'Username',
                'class': 'input-area form-control', }),
            'content': forms.TextInput(attrs={
                'placeholder': 'Comment',
                'class': 'input-area form-control', })
        }

templates/users/edit_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="title-container">
<h2>Edit Profile</h2>
</div>
<div class="form-container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.username.label_tag }}
            <input type="text" class="form-control input-area {% if form.username.errors %}is-invalid{% endif %}" id="id_username"
                name="username" value="{{ form.username.value|default:user.username }}">
            {% if form.username.errors %}
            <div class="invalid-feedback">
                {{ form.username.errors }}
            </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.bio.label_tag }}
            <textarea type="text" class="form-control input-area {% if form.bio.errors %}is-invalid{% endif %}"
                id="id_bio" name="bio"
                rows="5">{{ form.bio.value|default:user.profile.bio }}</textarea>
            {% if form.bio.errors %}
            <div class="invalid-feedback">
                {{ form.bio.errors }}
            </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.image.label_tag }}
            <input type="file" class="{% if form.image.errors %}is-invalid{% endif %}" id="id_image" name="image"
                accept="image/*">
            {% if form.image.errors %}
            <div class="invalid-feedback">
                {{ form.image.errors }}
            </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-outline-dark">Submit</button>
    </form>
</div>
{% endblock content %}

templates/users/login.html
{% extends 'base.html' %}
{% block content %}

<h1>Log in</h1>
<div class="form-container">
    <form method="POST">
{% csrf_token %}
{% if form.non_field_errors %}
{% for error in form_non_field_errors %}
{{ error }}
{% endfor %}
{% endif %}

{% for hidden in form_hidden_fields %}
{{ hidden }}
{% endfor %}

{% for field in form %}
{{ field.label_tag }}
<div class="form-group">{{ field }}</div>
{{ field.errors.as_ul }}
{% endfor %}
<button type="submit" class="btn btn-outline-dark">Log in</button>
    </form>
    </div>
{% endblock content %}

templates/users/password_change.html
{% extends 'base.html' %}
{% block content %}

<h1>Change Password</h1>
<div class="form-container">
    <form method="POST" class="form">
{% csrf_token %}
{% if form.non_field_errors %}
{% for error in form_non_field_errors %}
{{ error }}
{% endfor %}
{% endif %}

{% for hidden in form_hidden_fields %}
{{ hidden }}
{% endfor %}

{% for field in form %}
{{ field.label_tag }}
<div class="form-group">{{ field }}</div>
{{ field.errors.as_ul }}
{% endfor %}
<button class="btn btn-outline-dark" type="submit" value="submit">Submit</button>
    </form>
    </div>
{% endblock content %}

templates/users/password_change_done.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
        <div class="alert alert-success" role="alert">
            Your password has been changed successfully!
          </div>
          <a href="{% url 'magazine:home' %}" class="btn btn-outline-dark">Return to home page</a>
    </div>
</div>
{% endblock content %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="title-container">
<h2>Profile page</h2>
{% if user.is_authenticated %}
<h3>{{ user.username }}</h3>
</div>
<div class="profile-container">
   
    <div class="profile-picture">
            <img src="{{ profile.image.url }}" alt="{{ user.username }}" class="profile-image">
        </div>
    <p class="profile-bio">{{ user.profile.bio }}</p>
    <div class="profile-links">
        <p><a class="btn btn-outline-dark" href="{% url 'magazine:edit_profile' %}">Edit Profile</a></p>
        <p><a class="btn btn-outline-dark" href="{% url 'magazine:password_change' %}">Change Password</a></p>
        <p><a class="btn btn-outline-dark" href="{% url 'magazine:user_posts' request.user.username %}">My Posts</a></p>
    </div>
</div>
{% endif %}
{% endblock content %}

templates/users/signup.html
{% extends 'base.html' %}
{% block content %}

<h1>Sign up</h1>
<div class="form-container">
<form method="POST">
    {% csrf_token %}
    {% if form.non_field_errors %}
    {% for error in form_non_field_errors %}
    {{ error }}
    {% endfor %}
    {% endif %}
    
    {% for hidden in form_hidden_fields %}
    {{ hidden }}
    {% endfor %}
    
    {% for field in form %}
    {{ field.label_tag }}
    <div class="form-group">{{ field }}</div>
    {{ field.errors.as_ul }}
    {% endfor %}
    <button type="submit" class="btn btn-outline-dark">Signup</button>
</form>
</div>
{% endblock content %}

templates/users/user_posts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row blog-post-container">
    {% for post in object_list %}
  
    <div class="col post-container">
      <a class="post-image-link" href="{% url 'magazine:post_detail' post.pk post.slug %}">
        {% if post.image %}
        <img src="{{ post.image.url }}" alt="a blog post image that links to the blog post page with all of the post content {{ post.title }}" class="post-image">
  
        {% else %}
        <a class="post-image-link" href="{% url 'magazine:post_detail' post.pk post.slug %}">
          <img src="{% static 'img/default-post.jpg' %}" alt="a blog post image that links to the blog post page with all of the post content {{ post.title }}" class="post-image">
  
          {% endif %}
          <div class="post-body">
          <div class="author-created">
            <span class="">
              {{ post.author }} | {{ post.post_created }}
            </span>
            </div>
            <div class="title-description-container">
              <h2 class="post-title">{{ post.title }}</h2>
              <h3>{{ post.article_description }}</h3>
            </div>
          </div>
        </a>
    </div>
    {% endfor %}
  </div>
  {% endblock content %}